spring :
    servlet :
        multipart :
            max-file-size :    10MB
            max-request-size : 10MB
    datasource :


        url :      jdbc:mysql://localhost:3306/ticketrace_rest
        username: root
        password: 241105


    jpa :
        hibernate :
            ddl-auto : update
        show-sql : true


server :
    port : 8080
